---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reproducer
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/gmeghnag/03936486.git
    targetRevision: HEAD
    path: ./manifests/.
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    retry:
      limit: 3
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: '*'
    kind: '*'
    managedFieldsManagers:
    - kube-controller-manager
